// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AddSameCPFTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void addSameCPF() {
    driver.get("https://devhub.dev.br/");
    driver.manage().window().setSize(new Dimension(1936, 1056));
    driver.findElement(By.linkText("+ Adicionar")).click();
    driver.findElement(By.id("iCpf")).click();
    driver.findElement(By.id("iCpf")).click();
    driver.findElement(By.id("iCpf")).sendKeys("510.664.638-32");
    driver.findElement(By.id("iNome")).click();
    driver.findElement(By.id("iNome")).sendKeys("pedro");
    driver.findElement(By.id("iRua")).click();
    driver.findElement(By.id("iRua")).sendKeys("rua1");
    driver.findElement(By.id("iNumero")).click();
    driver.findElement(By.id("iNumero")).sendKeys("1");
    driver.findElement(By.id("iCep")).click();
    driver.findElement(By.id("iCep")).sendKeys("13569160");
    driver.findElement(By.id("iDataNasc")).click();
    driver.findElement(By.id("iDataNasc")).sendKeys("0002-12-21");
    driver.findElement(By.id("iDataNasc")).sendKeys("0020-12-21");
    driver.findElement(By.id("iDataNasc")).sendKeys("0200-12-21");
    driver.findElement(By.id("iDataNasc")).sendKeys("2002-12-21");
    driver.findElement(By.id("iProfissao")).click();
    driver.findElement(By.id("iProfissao")).sendKeys("seila");
    driver.findElement(By.id("cadastrarPessoa")).click();
    {
      WebElement element = driver.findElement(By.id("cadastrarPessoa"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
  }
}
