// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.support.ui.ExpectedConditions;

public class CheckIfCEPisValidTest {
  private WebDriver driver;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
  }
  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void checkIfCEPisValid() {

    driver.get("https://devhub.dev.br/");
    driver.manage().window().setSize(new Dimension(1936, 1056));


    driver.findElement(By.xpath("//img[@alt='Lapis - edicao']")).click();

   //cep inválido
    WebElement cepInput = driver.findElement(By.id("iCep"));
    cepInput.click();
    cepInput.sendKeys("135691601234");


    driver.findElement(By.id("cadastrarPessoa")).click();


    WebDriverWait wait = new WebDriverWait(driver, 10);
    WebElement errorMessage = wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".error-message")));
    assertNotNull("Erro: mensagem de validação não exibida!", errorMessage);


    String expectedMessage = "CEP inválido.";
    assertEquals("Erro: mensagem de validação incorreta!", expectedMessage, errorMessage.getText());
  }
}
